# Utiliser l'image MySQL officielle comme base
FROM postgres:17.4

# Copier les fichiers de configuration personnalisés si nécessaire
# COPY my.cnf /etc/mysql/conf.d/my.cnf

# Exposer le port MySQL
EXPOSE 3305

# Commande pour démarrer MySQL
CMD ["mysqld"]