services:
  node:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: node
    volumes:
      - ./api:/home/node/app/api
    ports:
      - "3000:3000"
    env_file:
      - .env

